apiVersion: v1 
kind: Secret
metadata:
  name: postgres-db-secret
  namespace: three-tier
type: Opaque
data: 
  POSTGRES_USER: Y2hldGFuX3VzZXI=
  POSTGRES_PASSWORD: Y2hldGFuMTIzNA==
  POSTGRES_DB: Y2hldGFuX2Ri     
